/**
 * Built-in themes. Each is plain data and may extend another by id. The
 * Qubibyte brand color comes from the project config.
 * @module themes/builtin
 */

import { PROJECT } from '../config.js';

/** @type {Array<Record<string, any>>} */
export const BUILTIN_THEMES = [
  {
    id: 'qubibyte',
    name: 'Qubibyte',
    dark: true,
    colors: {
      background: '#0e0f12',
      surface: '#16181d',
      ink: '#eeeae3',
      muted: '#9b978f',
      faint: '#57554f',
      grid: '#2a2c31',
      accent: PROJECT.brandColor,
      accent2: '#d9a441',
      positive: '#6fb58a',
      negative: '#d8735f',
      ket0: PROJECT.brandColor,
      ket1: '#d9a441',
      gateHadamard: PROJECT.brandColor,
      gatePauli: '#eeeae3',
      gatePhase: '#a391dc',
      gateRotation: '#6fb5a8',
      gateControlled: '#eeeae3',
      gateSwap: '#eeeae3',
      gateMeasure: '#9b978f',
      gateUser: '#d9a441',
    },
  },
  {
    id: 'clean-light',
    name: 'Clean Light',
    dark: false,
    colors: {
      background: '#faf9f6',
      surface: '#ffffff',
      ink: '#1b1b1d',
      muted: '#6b6862',
      faint: '#bcb8b0',
      grid: '#e4e1da',
      accent: '#2f5fd0',
      accent2: '#b8741c',
      positive: '#2f8a57',
      negative: '#c2452f',
      ket0: '#2f5fd0',
      ket1: '#b8741c',
      gateHadamard: '#2f5fd0',
      gatePauli: '#1b1b1d',
      gatePhase: '#6a52b8',
      gateRotation: '#2b8a7d',
      gateControlled: '#1b1b1d',
      gateSwap: '#1b1b1d',
      gateMeasure: '#6b6862',
      gateUser: '#b8741c',
    },
  },
  {
    id: 'clean-dark',
    name: 'Clean Dark',
    dark: true,
    colors: {
      background: '#131313',
      surface: '#1c1c1c',
      ink: '#f2f0ec',
      muted: '#9d9a94',
      faint: '#555350',
      grid: '#2c2b29',
      accent: '#4fb3a9',
      accent2: '#e0a458',
      positive: '#6fbf8e',
      negative: '#e07a66',
      ket0: '#4fb3a9',
      ket1: '#e0a458',
      gateHadamard: '#4fb3a9',
      gatePauli: '#f2f0ec',
      gatePhase: '#a99be0',
      gateRotation: '#4fb3a9',
      gateControlled: '#f2f0ec',
      gateSwap: '#f2f0ec',
      gateMeasure: '#9d9a94',
      gateUser: '#e0a458',
    },
  },
  {
    id: 'pastel',
    name: 'Pastel',
    dark: false,
    colors: {
      background: '#f5efe4',
      surface: '#fbf7f0',
      ink: '#4a443e',
      muted: '#8f867b',
      faint: '#cfc5b6',
      grid: '#e6dccd',
      accent: '#7aa3c7',
      accent2: '#e3a397',
      positive: '#98c29f',
      negative: '#e3a397',
      ket0: '#7aa3c7',
      ket1: '#e3a397',
      gateHadamard: '#7aa3c7',
      gatePauli: '#6f665c',
      gatePhase: '#b3a1d1',
      gateRotation: '#98c29f',
      gateControlled: '#6f665c',
      gateSwap: '#6f665c',
      gateMeasure: '#8f867b',
      gateUser: '#e3a397',
    },
    stroke: { regular: 5, bold: 7, axis: 3, grid: 2 },
    radius: { small: 0.08, medium: 0.16, large: 0.28 },
    motion: { ease: 'easeInOutSine', duration: 1.1 },
    texture: { grain: 0.35 },
  },
  {
    id: 'neon',
    name: 'Neon on Black',
    dark: true,
    colors: {
      background: '#060609',
      surface: '#0e0e14',
      ink: '#e6f4ff',
      muted: '#7c8898',
      faint: '#3a4150',
      grid: '#171b24',
      accent: '#35e8c6',
      accent2: '#ff5aa8',
      positive: '#35e8c6',
      negative: '#ff5aa8',
      ket0: '#35e8c6',
      ket1: '#ff5aa8',
      gateHadamard: '#35e8c6',
      gatePauli: '#e6f4ff',
      gatePhase: '#b48cff',
      gateRotation: '#35e8c6',
      gateControlled: '#e6f4ff',
      gateSwap: '#e6f4ff',
      gateMeasure: '#7c8898',
      gateUser: '#ff5aa8',
    },
    effects: { glow: 0.7 },
    background: { kind: 'solid', vignette: 0.5 },
  },
  {
    id: 'mono-ink',
    name: 'Monochrome Ink',
    dark: false,
    colors: {
      background: '#fbfaf7',
      surface: '#ffffff',
      ink: '#141414',
      muted: '#6f6f6f',
      faint: '#bdbdbd',
      grid: '#e2e2e2',
      accent: '#000000',
      accent2: '#5a5a5a',
      positive: '#141414',
      negative: '#6f6f6f',
      ket0: '#141414',
      ket1: '#8a8a8a',
      gateHadamard: '#141414',
      gatePauli: '#141414',
      gatePhase: '#141414',
      gateRotation: '#141414',
      gateControlled: '#141414',
      gateSwap: '#141414',
      gateMeasure: '#6f6f6f',
      gateUser: '#141414',
    },
    stroke: { regular: 3.5, axis: 2, grid: 1.2 },
  },
  {
    id: 'blueprint',
    name: 'Blueprint',
    dark: true,
    colors: {
      background: '#123a6b',
      surface: '#16447b',
      ink: '#eef4fb',
      muted: '#a9c1de',
      faint: '#5f82ad',
      grid: '#3a66a0',
      accent: '#ffffff',
      accent2: '#f4d58d',
      positive: '#bfe3c9',
      negative: '#f4b5a4',
      ket0: '#eef4fb',
      ket1: '#f4d58d',
      gateHadamard: '#eef4fb',
      gatePauli: '#eef4fb',
      gatePhase: '#eef4fb',
      gateRotation: '#eef4fb',
      gateControlled: '#eef4fb',
      gateSwap: '#eef4fb',
      gateMeasure: '#a9c1de',
      gateUser: '#f4d58d',
    },
    background: { kind: 'grid', spacing: 0.25, major: 4, opacity: 0.35, color: 'grid' },
    stroke: { regular: 3, axis: 2, grid: 1 },
  },
  {
    id: 'scientific-paper',
    name: 'Scientific Paper',
    dark: false,
    colors: {
      background: '#ffffff',
      surface: '#ffffff',
      ink: '#111111',
      muted: '#555555',
      faint: '#b0b0b0',
      grid: '#e3e3e3',
      accent: '#1f4e9c',
      accent2: '#b0391f',
      positive: '#1f6f3f',
      negative: '#b0391f',
      ket0: '#1f4e9c',
      ket1: '#b0391f',
      gateHadamard: '#111111',
      gatePauli: '#111111',
      gatePhase: '#111111',
      gateRotation: '#111111',
      gateControlled: '#111111',
      gateSwap: '#111111',
      gateMeasure: '#111111',
      gateUser: '#111111',
    },
    type: { text: 'KaTeX_Main', scale: { caption: 0.24, label: 0.28, body: 0.36 } },
    stroke: { regular: 2.5, axis: 1.6, grid: 1, thin: 1.6, hairline: 1 },
    motion: { ease: 'easeInOutCubic', duration: 0.9 },
  },
  {
    id: 'navy-explainer',
    name: 'Navy Explainer',
    dark: true,
    colors: {
      background: '#0b1422',
      surface: '#12203a',
      ink: '#f0efe9',
      muted: '#9aa5b6',
      faint: '#4a566b',
      grid: '#1d3150',
      accent: '#58c4dd',
      accent2: '#f2cf55',
      positive: '#83c167',
      negative: '#fc6255',
      ket0: '#58c4dd',
      ket1: '#f2cf55',
      gateHadamard: '#58c4dd',
      gatePauli: '#f0efe9',
      gatePhase: '#b39ddb',
      gateRotation: '#83c167',
      gateControlled: '#f0efe9',
      gateSwap: '#f0efe9',
      gateMeasure: '#9aa5b6',
      gateUser: '#f2cf55',
    },
  },
  {
    id: 'retro-terminal',
    name: 'Retro Terminal',
    dark: true,
    colors: {
      background: '#0a0e0a',
      surface: '#0f150f',
      ink: '#b7f2a0',
      muted: '#5f8c53',
      faint: '#2f4a2a',
      grid: '#1a2b18',
      accent: '#e8c86a',
      accent2: '#7fdcc2',
      positive: '#b7f2a0',
      negative: '#e8866a',
      ket0: '#b7f2a0',
      ket1: '#e8c86a',
      gateHadamard: '#e8c86a',
      gatePauli: '#b7f2a0',
      gatePhase: '#b7f2a0',
      gateRotation: '#b7f2a0',
      gateControlled: '#b7f2a0',
      gateSwap: '#b7f2a0',
      gateMeasure: '#5f8c53',
      gateUser: '#e8c86a',
    },
    type: { text: 'hershey:futural' },
    effects: { glow: 0.45, scanlines: 0.18 },
    background: { kind: 'solid', vignette: 0.6 },
    motion: { ease: 'easeOutCubic', duration: 0.8 },
  },
  {
    id: 'sepia-notebook',
    name: 'Sepia Notebook',
    dark: false,
    colors: {
      background: '#f2e8d2',
      surface: '#f7efdc',
      ink: '#3b2f22',
      muted: '#86735a',
      faint: '#c9b690',
      grid: '#dcc9a2',
      accent: '#8b3a2b',
      accent2: '#3e6a7a',
      positive: '#4f6f3a',
      negative: '#8b3a2b',
      ket0: '#3e6a7a',
      ket1: '#8b3a2b',
      gateHadamard: '#3e6a7a',
      gatePauli: '#3b2f22',
      gatePhase: '#3b2f22',
      gateRotation: '#3b2f22',
      gateControlled: '#3b2f22',
      gateSwap: '#3b2f22',
      gateMeasure: '#86735a',
      gateUser: '#8b3a2b',
    },
    type: { text: 'KaTeX_Main' },
    background: { kind: 'grid', spacing: 0.5, opacity: 0.55, color: 'grid' },
    texture: { grain: 0.5 },
  },
  {
    id: 'corporate-slide',
    name: 'Corporate Slide',
    dark: false,
    colors: {
      background: '#ffffff',
      surface: '#f4f5f7',
      ink: '#1d2433',
      muted: '#5d6678',
      faint: '#c3c8d2',
      grid: '#e7e9ee',
      accent: '#2957c4',
      accent2: '#e39a14',
      positive: '#1f8a5b',
      negative: '#c94a3a',
      ket0: '#2957c4',
      ket1: '#e39a14',
      gateHadamard: '#2957c4',
      gatePauli: '#1d2433',
      gatePhase: '#5d4db3',
      gateRotation: '#1f8a7a',
      gateControlled: '#1d2433',
      gateSwap: '#1d2433',
      gateMeasure: '#5d6678',
      gateUser: '#e39a14',
    },
    type: { scale: { title: 0.78, heading: 0.58, body: 0.42 } },
    radius: { small: 0.06, medium: 0.12, large: 0.2 },
    motion: { ease: 'easeOutCubic', duration: 0.7 },
  },
  {
    id: 'high-contrast',
    name: 'High Contrast',
    dark: true,
    colors: {
      background: '#000000',
      surface: '#111111',
      ink: '#ffffff',
      muted: '#d6d6d6',
      faint: '#8c8c8c',
      grid: '#5a5a5a',
      accent: '#ffd400',
      accent2: '#4cc9ff',
      positive: '#7ee787',
      negative: '#ff8a80',
      ket0: '#4cc9ff',
      ket1: '#ffd400',
      gateHadamard: '#ffd400',
      gatePauli: '#ffffff',
      gatePhase: '#ffffff',
      gateRotation: '#ffffff',
      gateControlled: '#ffffff',
      gateSwap: '#ffffff',
      gateMeasure: '#d6d6d6',
      gateUser: '#4cc9ff',
    },
    stroke: { regular: 5, axis: 3.5, grid: 2 },
    type: { scale: { caption: 0.3, label: 0.36, body: 0.44 } },
  },
  {
    id: 'chalkboard',
    name: 'Chalkboard',
    dark: true,
    colors: {
      background: '#1f3a2e',
      surface: '#24433a',
      ink: '#f1efe6',
      muted: '#b9c2b3',
      faint: '#6f8577',
      grid: '#3b5a4b',
      accent: '#f3d77e',
      accent2: '#9ed3e8',
      positive: '#b8e0a3',
      negative: '#f2a38f',
      ket0: '#9ed3e8',
      ket1: '#f3d77e',
      gateHadamard: '#f3d77e',
      gatePauli: '#f1efe6',
      gatePhase: '#f1efe6',
      gateRotation: '#f1efe6',
      gateControlled: '#f1efe6',
      gateSwap: '#f1efe6',
      gateMeasure: '#b9c2b3',
      gateUser: '#f2a38f',
    },
    board: 'chalkboard',
    boardOptions: { variant: 'green' },
    type: { hand: 'futural' },
    stroke: { regular: 5, axis: 4, grid: 2.5 },
  },
  {
    id: 'chalkboard-slate',
    extends: 'chalkboard',
    name: 'Chalkboard Slate',
    colors: { background: '#1c1f22', surface: '#23272a', grid: '#383d42', faint: '#666c72' },
    boardOptions: { variant: 'slate' },
  },
  {
    id: 'whiteboard',
    name: 'Whiteboard',
    dark: false,
    colors: {
      background: '#f7f8f7',
      surface: '#ffffff',
      ink: '#1f2a33',
      muted: '#5c6873',
      faint: '#b6bec4',
      grid: '#e2e6e8',
      accent: '#2e62b8',
      accent2: '#c23b36',
      positive: '#2e8a4e',
      negative: '#c23b36',
      ket0: '#2e62b8',
      ket1: '#c23b36',
      gateHadamard: '#2e62b8',
      gatePauli: '#1f2a33',
      gatePhase: '#1f2a33',
      gateRotation: '#2e8a4e',
      gateControlled: '#1f2a33',
      gateSwap: '#1f2a33',
      gateMeasure: '#5c6873',
      gateUser: '#c23b36',
    },
    board: 'whiteboard',
    boardOptions: { variant: 'white' },
    stroke: { regular: 5, axis: 4, grid: 2.5 },
  },
  {
    id: 'whiteboard-gray',
    extends: 'whiteboard',
    name: 'Whiteboard Gray',
    colors: { background: '#e9ebec', surface: '#f2f3f4' },
    boardOptions: { variant: 'gray' },
  },
  {
    id: 'paper',
    name: 'Paper',
    dark: false,
    colors: {
      background: '#fbf9f3',
      surface: '#ffffff',
      ink: '#26303a',
      muted: '#6d7680',
      faint: '#c3c8cc',
      grid: '#c9d6e3',
      accent: '#2f5aa8',
      accent2: '#b7791f',
      positive: '#3b7d4a',
      negative: '#b8412f',
      ket0: '#2f5aa8',
      ket1: '#b8412f',
      gateHadamard: '#2f5aa8',
      gatePauli: '#26303a',
      gatePhase: '#26303a',
      gateRotation: '#26303a',
      gateControlled: '#26303a',
      gateSwap: '#26303a',
      gateMeasure: '#6d7680',
      gateUser: '#b8412f',
    },
    board: 'paper',
    boardOptions: { ruling: 'ruled', tool: 'ballpoint' },
    stroke: { regular: 3.5, axis: 3, grid: 2 },
  },
  {
    id: 'board-blueprint',
    name: 'Blueprint Drafting',
    dark: true,
    colors: {
      background: '#123b6d',
      surface: '#16457c',
      ink: '#f1f6fb',
      muted: '#b0c7e2',
      faint: '#6389b5',
      grid: '#3c69a3',
      accent: '#ffffff',
      accent2: '#f4d58d',
      positive: '#c7ead0',
      negative: '#f6bcae',
      ket0: '#f1f6fb',
      ket1: '#f4d58d',
      gateHadamard: '#f1f6fb',
      gatePauli: '#f1f6fb',
      gatePhase: '#f1f6fb',
      gateRotation: '#f1f6fb',
      gateControlled: '#f1f6fb',
      gateSwap: '#f1f6fb',
      gateMeasure: '#b0c7e2',
      gateUser: '#f4d58d',
    },
    board: 'blueprint',
    boardOptions: {},
    stroke: { regular: 3, axis: 2.5, grid: 1.5 },
  },
];
